export {default as Blog} from './blog/Blog'
export {default as Features} from './features/Feature'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as Possibility} from './possibilty/Possibility'
export {default as Whatgpt3} from './whatGPT3/Whatgpt3'